"""
api.py — SONiC route consistency checker: FastAPI REST server

Exposes collector + diff engine results as REST endpoints.
The OpenAPI schema auto-generated by FastAPI is directly usable by
LangGraph for tool definitions.

Environment variables:
    SONIC_HOST      Redis host (default: 127.0.0.1)
    SONIC_REDIS_PORT Redis port (default: 6379)

Run:
    uvicorn checker.api:app --reload --host 0.0.0.0 --port 8000
"""

import os
import time
import urllib.parse
from typing import Optional

import redis
from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel

from .collector import RouteCollector, RouteSnapshot, RouteEntry
from .diff_engine import DiffEngine, Inconsistency


# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------

app = FastAPI(
    title="SONiC Route Consistency Checker",
    description=(
        "Compares routing state across FRR RIB, APP_DB, ASIC_DB, and Kernel FIB. "
        "Detects inconsistencies and exposes them for AI-assisted root cause analysis."
    ),
    version="0.1.0",
)

# In-memory snapshot cache (last collected)
_snapshot: Optional[RouteSnapshot] = None
_snapshot_time: float = 0.0
_CACHE_TTL = 30  # seconds before snapshot is considered stale


def _get_collector() -> RouteCollector:
    host = os.environ.get("SONIC_HOST", "127.0.0.1")
    port = int(os.environ.get("SONIC_REDIS_PORT", "6379"))
    return RouteCollector(host=host, redis_port=port)


def _get_snapshot(force: bool = False) -> RouteSnapshot:
    global _snapshot, _snapshot_time
    if force or _snapshot is None or (time.time() - _snapshot_time) > _CACHE_TTL:
        _snapshot = _get_collector().collect()
        _snapshot_time = time.time()
    return _snapshot


# ---------------------------------------------------------------------------
# Response models
# ---------------------------------------------------------------------------

class HealthResponse(BaseModel):
    status: str
    redis_app_db: str
    redis_asic_db: str
    snapshot_age_seconds: Optional[float] = None


class SnapshotSummary(BaseModel):
    timestamp: float
    app_db_routes: int
    asic_db_routes: int
    frr_routes: int
    kernel_routes: int
    collected_at: str


class RouteEntryModel(BaseModel):
    prefix: str
    nexthops: list[str]
    interfaces: list[str]
    protocol: Optional[str]
    metric: Optional[int]
    vrf: str


class RouteCrossPlane(BaseModel):
    prefix: str
    frr: Optional[RouteEntryModel]
    app_db: Optional[RouteEntryModel]
    asic_db: Optional[RouteEntryModel]
    kernel: Optional[RouteEntryModel]


class InconsistencyModel(BaseModel):
    prefix: str
    vrf: str
    present_in: list[str]
    missing_in: list[str]
    nexthop_mismatch: dict[str, list[str]]
    severity: str
    diagnosis: str


class InconsistenciesResponse(BaseModel):
    snapshot_timestamp: float
    total: int
    critical: int
    warning: int
    info: int
    inconsistencies: list[InconsistencyModel]


class HistoryEvent(BaseModel):
    timestamp: float
    event_type: str   # "hset" or "del"
    prefix: str
    plane: str


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _route_to_model(entry: Optional[RouteEntry]) -> Optional[RouteEntryModel]:
    if entry is None:
        return None
    return RouteEntryModel(
        prefix=entry.prefix,
        nexthops=entry.nexthops,
        interfaces=entry.interfaces,
        protocol=entry.protocol,
        metric=entry.metric,
        vrf=entry.vrf,
    )


def _inconsistency_to_model(i: Inconsistency) -> InconsistencyModel:
    return InconsistencyModel(
        prefix=i.prefix,
        vrf=i.vrf,
        present_in=i.present_in,
        missing_in=i.missing_in,
        nexthop_mismatch=i.nexthop_mismatch,
        severity=i.severity,
        diagnosis=i.diagnosis,
    )


def _find_route_in_plane(
    plane: dict[str, RouteEntry], prefix: str
) -> Optional[RouteEntry]:
    """Lookup with canonical prefix normalization."""
    from ipaddress import ip_network
    try:
        canonical = str(ip_network(prefix, strict=False))
    except ValueError:
        canonical = prefix

    if canonical in plane:
        return plane[canonical]
    for k, v in plane.items():
        try:
            if str(ip_network(k, strict=False)) == canonical:
                return v
        except ValueError:
            pass
    return None


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/health", response_model=HealthResponse, tags=["infra"])
def health() -> HealthResponse:
    """
    Check Redis connectivity for both APP_DB and ASIC_DB.
    Returns status "ok" if both are reachable, "degraded" otherwise.
    """
    host = os.environ.get("SONIC_HOST", "127.0.0.1")
    port = int(os.environ.get("SONIC_REDIS_PORT", "6379"))

    def ping(db: int) -> str:
        try:
            r = redis.Redis(host=host, port=port, db=db, socket_timeout=2)
            r.ping()
            return "ok"
        except Exception as exc:
            return f"error: {exc}"

    app_status  = ping(0)
    asic_status = ping(1)
    overall = "ok" if app_status == "ok" and asic_status == "ok" else "degraded"
    age = (time.time() - _snapshot_time) if _snapshot is not None else None

    return HealthResponse(
        status=overall,
        redis_app_db=app_status,
        redis_asic_db=asic_status,
        snapshot_age_seconds=age,
    )


@app.post("/snapshot", response_model=SnapshotSummary, tags=["collection"])
def take_snapshot() -> SnapshotSummary:
    """
    Trigger a fresh collection from all four planes and cache it.
    Use this to force a refresh before querying /inconsistencies.
    """
    snap = _get_snapshot(force=True)
    return SnapshotSummary(
        timestamp=snap.timestamp,
        app_db_routes=len(snap.app_db),
        asic_db_routes=len(snap.asic_db),
        frr_routes=len(snap.frr),
        kernel_routes=len(snap.kernel),
        collected_at=time.ctime(snap.timestamp),
    )


@app.get("/inconsistencies", response_model=InconsistenciesResponse, tags=["analysis"])
def get_inconsistencies(raw: bool = Query(False, description="If true, disable noise suppression and return all inconsistencies including SAI-internal, management-plane, and kernel-internal entries.")) -> InconsistenciesResponse:
    """
    Run the diff engine on the latest snapshot and return all detected
    cross-plane inconsistencies, sorted by severity (critical first).

    Use ?raw=true to disable noise suppression and see all inconsistencies
    including expected-benign SONiC-VS entries (SAI-internal, mgmt-plane, etc.).
    """
    snap = _get_snapshot()
    engine = DiffEngine(snap)
    issues = engine.diff(suppress_noise=not raw)

    severity_order = {"critical": 0, "warning": 1, "info": 2}
    issues.sort(key=lambda i: severity_order.get(i.severity, 99))

    counts = {"critical": 0, "warning": 0, "info": 0}
    for i in issues:
        counts[i.severity] = counts.get(i.severity, 0) + 1

    return InconsistenciesResponse(
        snapshot_timestamp=snap.timestamp,
        total=len(issues),
        critical=counts["critical"],
        warning=counts["warning"],
        info=counts["info"],
        inconsistencies=[_inconsistency_to_model(i) for i in issues],
    )


@app.get("/routes/{prefix:path}", response_model=RouteCrossPlane, tags=["analysis"])
def get_route(prefix: str) -> RouteCrossPlane:
    """
    Return the per-prefix routing state across all four planes.

    The prefix should be URL-encoded if it contains slashes, e.g.:
        GET /routes/10.1.0.0%2F24

    Returns null for a plane if the route is not present there.
    """
    # FastAPI path param captures slashes when using {prefix:path}
    snap = _get_snapshot()

    return RouteCrossPlane(
        prefix=prefix,
        frr=_route_to_model(_find_route_in_plane(snap.frr, prefix)),
        app_db=_route_to_model(_find_route_in_plane(snap.app_db, prefix)),
        asic_db=_route_to_model(_find_route_in_plane(snap.asic_db, prefix)),
        kernel=_route_to_model(_find_route_in_plane(snap.kernel, prefix)),
    )


@app.get("/history/{prefix:path}", response_model=list[HistoryEvent], tags=["analysis"])
def get_history(prefix: str, limit: int = 50) -> list[HistoryEvent]:
    """
    Return the recent Redis keyspace event log for a prefix from APP_DB.

    Requires keyspace notifications enabled on the SONiC box:
        redis-cli config set notify-keyspace-events KEA

    This endpoint reads from a Redis Stream named
    ``route_history:<canonical_prefix>`` that is populated by a separate
    subscriber process (e.g. ``RouteCollector.subscribe_changes()``).
    If no history stream exists, returns an empty list.
    """
    from ipaddress import ip_network

    host = os.environ.get("SONIC_HOST", "127.0.0.1")
    port = int(os.environ.get("SONIC_REDIS_PORT", "6379"))

    try:
        canonical = str(ip_network(prefix, strict=False))
    except ValueError:
        canonical = prefix

    try:
        r = redis.Redis(host=host, port=port, db=0, socket_timeout=2,
                        decode_responses=True)
        stream_key = f"route_history:{canonical}"
        entries = r.xrevrange(stream_key, count=limit)
    except Exception:
        return []

    events: list[HistoryEvent] = []
    for entry_id, fields in entries:
        # Stream ID format: <unix-ms>-<seq>
        ts_ms = int(entry_id.split("-")[0])
        events.append(HistoryEvent(
            timestamp=ts_ms / 1000.0,
            event_type=fields.get("event", "unknown"),
            prefix=fields.get("prefix", canonical),
            plane=fields.get("plane", "app_db"),
        ))

    return events
